### ISSUE TITLE
Estonia intends to cancel the requirement to licence X-road code with EUPL

### ISSUE THREAD

**Issue by tormi** [educloudalliance/xroad-rest-gateway#16]
[RIA](https://www.ria.ee/) has prepared [an amendment](https://eelnoud.valitsus.ee/main/mount/docList/6f38d0b5-1a6f-46a5-b174-5a4376e75fd7) which cancels the requirement to use an EUPL licence from [X-road legislation](https://www.riigiteataja.ee/akt/128112014017?leiaKehtiv#para21) (section 4). @andreskytt , what is the reasoning behind this?

**Comment by tormi** [comment]
Ok, got some additional information - the reason is not to be that restrictive as particular licence is. Licencing principles will not change, but intention is to enable some other open source licences as options (MIT is under consideration).

**Comment by hillar** [comment]
can you please  point to the source of "..intention is to enable some other open source licences.."

**Comment by tormi** [comment]
Snapshot from modified explanatory note initiated by me (modified by Laura Kask from MKM, agreed with Heiko Vainsalu from RIA this morning):
![x-tee_litsents](https://cloud.githubusercontent.com/assets/146800/9629049/82aa6bca-5178-11e5-8c60-5aabba8e5a8c.PNG)
