### ISSUE TITLE
ProviderGateway should accept application/xml content type as REST service response

### ISSUE THREAD

**Issue by tsallinen** [educloudalliance/xroad-rest-gateway#17]
Currently Provider accepts only text/xml and application/json content-type:

https://github.com/educloudalliance/xroad-rest-gateway/blob/master/src/src/main/java/com/pkrete/xrd4j/tools/rest_gateway/ProviderGateway.java#L127

As application/xml is fairly common, perhaps it should be supported as an alternative form to text/xml.

**Comment by petkivim** [comment]
You're right, application/xml should be supported. Now it's added.
