### ISSUE TITLE
Closing xroad-rest-gateway repository

### ISSUE THREAD

**Issue by hanhaka** [educloudalliance/xroad-rest-gateway#31]
Hi,

we have moved the xroad-rest-gateway repository under VRK's GitHub account to be more closely a part of Finnish X-Road. For more information about the moving, see [#26](https://github.com/educloudalliance/xroad-rest-gateway/issues/26). 

New repository locates now here: https://github.com/vrk-kpa/REST-adapter-service
There can be found the latest version of component. This version includes some further development work & updated instructions for using it etc.

Could you close down the xroad-rest-gateway repository (or change it to be an Private Repository)?
Currently it confuses Finnish X-Road users and developers as there are two existing repositories for pretty much same purpose.

Thanks,
Hannu
Suomi.fi-palveluväylä (X-Road) Product Owner

**Comment by petkivim** [comment]
Added a note in the repository's description and README.md that this repository is no longer maintained and a link to the new repository. However, this repository will be kept for archive purposes.
